// Generated by gencpp from file nav_msgs/MapMetaData.msg
// DO NOT EDIT!


#ifndef NAV_MSGS_MESSAGE_MAPMETADATA_H
#define NAV_MSGS_MESSAGE_MAPMETADATA_H


#include <string>
#include <vector>
#include <map>

namespace walle {
    struct MapMetaData {

        MapMetaData()
                : resolution(0.0), width(0), height(0) {
        }

        float resolution;

        uint32_t width;

        uint32_t height;


        typedef std::shared_ptr<::walle::MapMetaData> Ptr;
        typedef std::shared_ptr<::walle::MapMetaData const> ConstPtr;

    }; // struct MapMetaData_

    typedef std::shared_ptr<::walle::MapMetaData> MapMetaDataPtr;
    typedef std::shared_ptr<::walle::MapMetaData const> MapMetaDataConstPtr;

}
#endif // NAV_MSGS_MESSAGE_MAPMETADATA_H
